name: Deploy to AWS ECS

on:
  push:
    branches:
      - master  # Runs when code is pushed to the main branch

jobs:
  deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS Credentials (Consider using OIDC instead of access keys)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build, Tag, and Push Docker Image to ECR
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: quest-container-repository
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Get current task definition
        run: |
          aws ecs describe-task-definition --task-definition quest-task:1 \
            --query "taskDefinition.{family: family, taskRoleArn: taskRoleArn, executionRoleArn: executionRoleArn, networkMode: networkMode, containerDefinitions: containerDefinitions, requiresCompatibilities: requiresCompatibilities, cpu: cpu, memory: memory}" > task-definition.json

      - name: Validate task-definition.json exists
        run: |
          if [ ! -f task-definition.json ]; then
            echo "Error: task-definition.json not found!"
            exit 1
          fi
          echo "task-definition.json successfully created."

      - name: Validate task definition parameters
        run: |
          REQUIRED_KEYS='["family", "taskRoleArn", "executionRoleArn", "networkMode", "containerDefinitions", "requiresCompatibilities", "cpu", "memory"]'
          INVALID_KEYS=$(jq -r 'keys_unsorted - $REQUIRED_KEYS | .[]' task-definition.json)

          if [ -n "$INVALID_KEYS" ]; then
            echo "Error: Found invalid parameters in task-definition.json:"
            echo "$INVALID_KEYS"
            exit 1
          fi
          echo "Task definition parameters validated successfully."

      - name: Register new task definition with updated image
        run: |
          jq --arg IMG "$ECR_IMAGE" '.containerDefinitions[0].image = $IMG' task-definition.json > new-task-def.json
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)

      - name: Update ECS Service with new task definition
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $TASK_DEF_ARN
