name: Terraform CI/CD

on:
  push:
    branches:
      - master # Runs only on pushes to the master branch

jobs:
  terraform-lint:
    name: Lint and Format Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - run: tflint --format compact

  terraform-security:
    name: Run tfsec Security Scan
    runs-on: ubuntu-latest
    needs: terraform-lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .
          soft_fail: false # Fail the workflow if tfsec finds issues

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-security # Runs only if security scan passes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_region: "us-east-1" # Set environment variables if needed
